// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP-gdkI-QHC5sBWgr8n8XvqunyQ7l-8-s',
    appId: '1:880964926822:android:44b269d3a47465b6569ca7',
    messagingSenderId: '880964926822',
    projectId: 'foodapp-d2100',
    storageBucket: 'foodapp-d2100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwnA67Xt7JRcx-2wvD1eUsl5F1j5PF1yE',
    appId: '1:880964926822:ios:889c3b2763ba06dc569ca7',
    messagingSenderId: '880964926822',
    projectId: 'foodapp-d2100',
    storageBucket: 'foodapp-d2100.firebasestorage.app',
    iosBundleId: 'com.example.foodAppImakes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAki4mV6tpqScdhrpQDBpHOv01bNViUnUQ',
    appId: '1:880964926822:web:f830ba2015c52a33569ca7',
    messagingSenderId: '880964926822',
    projectId: 'foodapp-d2100',
    authDomain: 'foodapp-d2100.firebaseapp.com',
    storageBucket: 'foodapp-d2100.firebasestorage.app',
    measurementId: 'G-3D7BCGYVXF',
  );
}/*const firebaseConfig = {
  apiKey: "AIzaSyAki4mV6tpqScdhrpQDBpHOv01bNViUnUQ",
  authDomain: "foodapp-d2100.firebaseapp.com",
  projectId: "foodapp-d2100",
  storageBucket: "foodapp-d2100.firebasestorage.app",
  messagingSenderId: "880964926822",
  appId: "1:880964926822:web:80a45223d6d07a1f569ca7",
  measurementId: "G-6X5J3EFR0H"
};
*/